name: Deployment

on:

  schedule:
    - cron: '0 12 * * 0'

  workflow_dispatch:

    branches:
      - master
      - development
      - development_*

    inputs:
    
      version:
        description: 'Dear PyGui Version'
        required: false
        default: '0.0.1'
    
      deploy:
        description: 'Deploy (true will deploy to pypi)'
        required: false
        default: 'false'
    
      deploytest:
        description: 'Deploy (true will deploy to test pypi)'
        required: false
        default: 'false'

jobs:
  build-linux-wheels:

    runs-on: ubuntu-18.04
    env:
      CXX: g++-9
    strategy:
      matrix:
        python-version: [ 3.6 ]

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Retrieve submodules/Dependencies
      run: |
        git submodule update --init --recursive ./Dependencies/imgui
        git submodule update --init --recursive ./Dependencies/freetype
        git submodule update --init --recursive ./Dependencies/glfw
        sudo apt-get update
        sudo apt-get install libglu1-mesa-dev libgl1-mesa-dev xorg-dev libxrandr-dev -y
        sudo apt-get install libfreetype6-dev -y
        sudo apt-get install libharfbuzz-dev -y
    
    - name: Mark Versions
      run: |
        cd $GITHUB_WORKSPACE
        echo ${{ github.event.inputs.version }} > version_number.txt

    - name: Build Wheel
      run: |
        cd $GITHUB_WORKSPACE
        python -m pip install --upgrade pip twine wheel
        python -m setup bdist_wheel --plat-name manylinux1_x86_64 --dist-dir dist

    - name: Upload Linux ${{ matrix.python-version }} Wheel
      uses: actions/upload-artifact@v2
      with:
        name: linuxbuild${{ matrix.python-version }}
        path: ${{ github.workspace }}/dist/*.whl
        retention-days: 2

  build-linux-aarch64-wheels:
    runs-on: ubuntu-18.04
    env:
      py: /opt/python/${{ matrix.python-version }}/bin/python
      img: quay.io/pypa/manylinux2014_aarch64
    strategy:
      matrix:
        python-version: ['cp36-cp36m']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Building Linux Aarch64 Wheel
      run: |
        docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
        ${{ env.img }} \
        bash -exc '${{ env.py }} -m venv .env && \
        source .env/bin/activate && \
        echo "Retrieve submodules/Dependencies" && \
        git submodule update --init --recursive ./Dependencies/imgui && \
        git submodule update --init --recursive ./Dependencies/freetype && \
        git submodule update --init --recursive ./Dependencies/glfw && \
        yum update -y && \
        yum install mesa-libGLU-devel mesa-libGL-devel xorg-x11-server-devel libXrandr-devel -y && \
        yum install freetype-devel harfbuzz -y && \
        yum install python3-devel libffi-devel wget -y && \
        curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=stable && \
        export PATH="$HOME/.cargo/bin:$PATH" && \
        #wget https://ftp.openssl.org/source/old/1.1.1/openssl-1.1.1.tar.gz --no-check-certificate && \
        #tar xvf openssl-1.1.1.tar.gz && \
        #cd openssl-1.1.1/ && \
        #./config --prefix=/usr --openssldir=/etc/ssl --libdir=lib no-shared zlib-dynamic && \
        #make && make install && \
        #cd .. && \
        pip install --upgrade pip twine wheel setuptools && \
        yum install libXinerama-devel libXcursor-devel libXi-devel -y && \
        python --version && \
        python -m setup bdist_wheel --plat-name manylinux2014_aarch64 --dist-dir dist && \
        deactivate'
  deploy-packages:

    needs: [build-linux-wheels]
    runs-on: windows-2019

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel twine

    - name: Download artifacts
      uses: actions/download-artifact@v2

    - name: PyPi Deployment
      shell: cmd
      if: ${{contains(github.event.inputs.deploy, 'true') && github.ref == 'refs/heads/master'}}
      run: |
        python -m twine upload windowsbuild*/* -u __token__ -p ${{ secrets.PYPI_PASSWORD }} --skip-existing
        python -m twine upload apple10build*/* -u __token__ -p ${{ secrets.PYPI_PASSWORD }} --skip-existing
        python -m twine upload linuxbuild*/* -u __token__ -p ${{ secrets.PYPI_PASSWORD }} --skip-existing

    - name: Test PyPi Deployment
      shell: cmd
      if: "contains(github.event.inputs.deploytest, 'true')"
      run: |
        dir
        python -m twine upload --repository testpypi windowsbuild*/* -u __token__ -p ${{ secrets.TEST_PYPI_PASSWORD }} --skip-existing
        python -m twine upload --repository testpypi apple10build*/* -u __token__ -p ${{ secrets.TEST_PYPI_PASSWORD }} --skip-existing
        python -m twine upload --repository testpypi linuxbuild*/* -u __token__ -p ${{ secrets.TEST_PYPI_PASSWORD }} --skip-existing
